# APIs/docker‐compose.yml
version: '3.8'
services:
  mongo:
    image: mongo:6.0
    container_name: townkitchen-mongo
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: townkitchen-backend
    restart: unless-stopped
    ports:
      - '5000:5000'
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/townkitchen

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: townkitchen-frontend
    restart: unless-stopped
    ports:
      - '3000:80'
    depends_on:
      - backend

volumes:
  mongo_data:
